baseURL = 'https://sovereign-cloud.nl'
languageCode = 'en-us'
title = 'Sovereign Cloud NL Community'
theme = 'clarity'

[params]
logo = 'images/sovereign-cloud-logo-left.png'
enableSearch = true

[menu]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = -110

[[menu.main]]
  name = "Blogs"
  url = "posts/"
  weight = -109

[[menu.main]]
  name = "Archive"
  url = "/archive/"
  weight = -108

[[menu.main]]
  name = "About"
  url = "about/"
  weight = -107

# Submenus are done this way: parent -> identifier
[[menu.main]]
  name = "Links"
  identifier = "Links"
  weight = -106
[[menu.main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/sovereign-cloud-nl-community"
[[menu.main]]
  parent = "Links"
  name = "Cloud for Sovereignty"
  url = "https://cloudforsovereignty.org"
[[menu.main]]
  parent = "Links"
  name = "Microsoft Docs"
  url = "https://learn.microsoft.com/en-us/industry/sovereignty/"

  
# social menu links

[[menu.social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/sovereign-cloud"
[[menu.social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#sovereign-cloud-nl"
 [[menu.social]]
   name = "linkedin"
   weight = 3
   url = "https://www.linkedin.com/company/sovereign-cloud-nl-community"


[taxonomies]
category = "categories"
tag = "tags"

showShare = true

[outputs]
home = ["HTML", "RSS", "JSON"]