[[main]]
  name = "Home"
  url = "/"
  weight = -110

[[main]]
  name = "Blog"
  url = "posts/"
  weight = -109

[[main]]
  name = "Archive"
  url = "archive/"
  weight = -108

[[main]]
  name = "About"
  url = "about/"
  weight = -107

[[main]]
  name = "Contact"
  url = "contact/"
  weight = -106

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -106
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/sovereign-cloud-nl-community"
[[main]]
  parent = "Links"
  name = "Microsoft Docs - Confidential Compute"
  url = "https://azure.microsoft.com/en-gb/solutions/confidential-compute"
[[main]]
  parent = "Links"
  name = "Microsoft Docs - Cloud for Sovereignty"
  url = "https://learn.microsoft.com/en-us/industry/sovereignty/"
[[main]]
  parent = "Links"
  name = "CCF - Confidential Consortium Framework"
  url = "https://ccf.microsoft.com/"
[[main]]
  parent = "Links"
  name = "CCC - Confidential Computing Consortium"
  url = "https://confidentialcomputing.io/"
[[main]]
  parent = "Links"
  name = "Edgeless Systems - Multi-Cloud Security"
  url = "https://www.edgeless.systems/"

  
# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/sovereign-cloud"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/#sovereign-cloud-nl"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/company/sovereign-cloud-nl-community"
